name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        make pip
    - name: Lint
      run: |
        make linting_test
    - name: Tests
      run: |
        make pytest_test
    - name: Archive report
      uses: actions/upload-artifact@v2
      with:
          name: reports
          path: reports
